# 1. Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:
   Region A: [10, 15, 12, 8, 14]
   Region B: [18, 20, 16, 22, 25]
   Calculate the mean sales for each region


In [3]:
import statistics
 
# list of positive integer numbers
Region_a = [10,15,12,8,14]
Region_b = [18,20,16,22,25]
 
reg1 = statistics.mean(Region_a)
reg2 = statistics.mean(Region_b)
# Printing the mean
print("Mean is :", reg1)
print("Mean is :", reg2)

Mean is : 11.8
Mean is : 20.2


# 2. Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
   Calculate the mode of the survey responses.


In [7]:
import statistics

data=[4, 5, 2, 3, 5, 4, 3, 2, 4, 5]

print("Mode of given dataset is :" ,(statistics.mode(data)))

Mode of given dataset is : 4


# 3. Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:
   Department A: [5000, 6000, 5500, 7000]
   Department B: [4500, 5500, 5800, 6000, 5200]
   Calculate the median salary for each department.


In [8]:
import statistics
Department_a = [5000, 6000, 5500, 7000]
Department_b = [4500, 5500, 5800, 6000, 5200] 

print("mean salary for department a :",(statistics.median(Department_a)))
print("mean salary for department b :",(statistics.median(Department_b)))


mean salary for department a : 5750.0
mean salary for department b : 5500


# 4. Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:
   [25.5, 24.8, 26.1, 25.3, 24.9]
   Calculate the range of the stock prices.


In [10]:

data = [25.5, 24.8, 26.1, 25.3, 24.9] 

range1 = max(data) - min(data)
print(" The range of the data is : ",range1)


 The range of the data is :  1.3000000000000007


# 5. Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:
   Group A: [85, 90, 92, 88, 91]
   Group B: [82, 88, 90, 86, 87]
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.


In [11]:
from statsmodels.stats.weightstats import ttest_ind

group_a = [85, 90, 92, 88, 91] 
group_b = [82, 88, 90, 86, 87]

ttest_ind(group_a, group_b)

# The p-value of the test comes out to be equal to 0.190
#which is greater than the significance level alpha (that is, 0.05).
#This implies that we can say that the average  of students in one group is statistically
#not different from the average  of students in another group. 

(1.4312528946642733, 0.19023970239078333, 8.0)

# 6. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
   Sales (in thousands): [25, 30, 28, 20, 26]
   Calculate the correlation coefficient between advertising expenditure and sales.


In [15]:
import scipy.stats
import numpy as np

adv =  [10, 15, 12, 8, 14]
sales = [25, 30, 28, 20, 26]

pearsons_coefficient = np.corrcoef(adv, sales)
print("The pearson's coeffient of the adv and sales inputs are: \n" ,pearsons_coefficient)

The pearson's coeffient of the adv and sales inputs are: 
 [[1.         0.87575114]
 [0.87575114 1.        ]]


# 7. Scenario: A survey is conducted to measure the heights of a group of people. The data collected is as follows:
   [160, 170, 165, 155, 175, 180, 170]
   Calculate the standard deviation of the heights


In [16]:
import statistics
 
# creating a simple data - set
sample = [160, 170, 165, 155, 175, 180, 170]
 
# Prints standard deviation
# xbar is set to default value of 1
print("Standard Deviation of sample is % s "
                % (statistics.stdev(sample)))

Standard Deviation of sample is 8.591246929842246 


# 8. Scenario: A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]
   Perform a linear regression analysis to predict job satisfaction based on employee tenure.


In [35]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

employee_Tenure = [2, 3, 5, 4, 6, 2, 4] 
job_Satisfaction = [7, 8, 6, 9, 5, 7, 6] 
data =pd.DataFrame({'employee_Tenure':[2, 3, 5, 4, 6, 2, 4],'job_Satisfaction':[7, 8, 6, 9, 5, 7, 6] })
x = data.iloc[: , :-1]
y = data.iloc[: , 1:2]
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=1/3,random_state=0)
regressor = LinearRegression()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test) 
y_pred

array([[6.81818182],
       [6.45454545],
       [7.18181818]])

# 9. Scenario: A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:
   Medication A: [10, 12, 14, 11, 13]
   Medication B: [15, 17, 16, 14, 18]
   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications.


In [36]:
from scipy.stats import f_oneway

med_a = [10, 12, 14, 11, 13]
med_b = [15, 17, 16, 14, 18]

f_oneway(med_a , med_b)

#The F statistic and p-value turn out to be equal to 16.0 and 0.0039 respectively.
#Since the p-value is less than 0.05 hence we would reject the null hypothesis.
#This implies that we have sufficient proof to say that there exists a difference in the performance among two different medications. 

F_onewayResult(statistic=16.0, pvalue=0.003949772803445326)

# 10. Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is

 as follows:
    [8, 9, 7, 6, 8, 10, 9, 8, 7, 8]
    Calculate the 75th percentile of the feedback ratings.


In [37]:
import numpy as np

arr = [8, 9, 7, 6, 8, 10, 9, 8, 7, 8] 

print("75th percentile of arr : ",
       np.percentile(arr, 75))

75th percentile of arr :  8.75


# 11. Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.


In [40]:
# h0(null hypethesis) - weight differs significantly from 10 grams 
# h1(alternate hypethesis) - weight not differs significantly from 10 grams

from scipy.stats import ttest_1samp  
import numpy as np 

sample = [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]

mean = np.mean(sample)
print(mean)

 # Performing the T-Test   
t_test, p_val = ttest_1samp(sample, 10.15)  
print("P-value is: ", p_val) 

# taking the threshold value as 0.05 or 5%  
if p_val < 0.05:      
    print(" We can reject the null hypothesis")  
else:  
    print("We can accept the null hypothesis") 

10.15
P-value is:  1.0
We can accept the null hypothesis


# 12. Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:
    Design A: [100, 120, 110, 90, 95]
    Design B: [80, 85, 90, 95, 100]
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs


In [42]:
# h0(null hypethesis) - there is a significant difference in the click-through rates between the two designs
# h1(alternate hypethesis) - there is no significant difference in the click-through rates between the two designs
from scipy.stats import chi2_contingency  
    
# defining our data  
data = [[100, 120, 110, 90, 95], [80, 85, 90, 95, 100]]

# Performing chi-square test  
test, p_val, dof, expected_val = chi2_contingency(data) 

# interpreting the p-value  
alpha = 0.05  
print("The p-value of our test is " + str(p_val))

# Checking the hypothesis  
if p_val <= alpha:  
    print('We can reject the null hypothesis')  
else:  
    print('We can accept the null hypothesis') 

The p-value of our test is 0.19103526314060293
We can accept the null hypothesis


# 13. Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
    Calculate the 95% confidence interval for the population mean satisfaction score.


In [45]:
import numpy as np 
from scipy.stats import t

sample = [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]
x=np.array(sample)

m = x.mean() 
s = x.std() 
dof = len(x)-1 
confidence = 0.95

t_crit = np.abs(t.ppf((1-confidence)/2,dof))

(m-s*t_crit/np.sqrt(len(x)), m+s*t_crit/np.sqrt(len(x)))

values = [np.random.choice(x,size=len(x),replace=True).mean() for i in range(1000)] 
np.percentile(values,[100*(1-confidence)/2,100*(1-(1-confidence)/2)])

array([7.2, 8.7])

# 14. Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]
    Perform a simple linear regression to predict performance based on temperature.


In [49]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.DataFrame({'Temperature':[20, 22, 23, 19, 21],'Performance':[8, 7, 9, 6, 8]})
x = data.iloc[: , :-1]
y = data.iloc[: , 1:2]
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=1/3,random_state=0)
regressor = LinearRegression()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test) 
y_pred

array([[8.        ],
       [6.71428571]])

# 15. Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:
    Group A: [4, 3, 5, 2, 4]  Group B: [3, 2, 4, 3, 3]
    Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.

In [50]:
from scipy.stats import mannwhitneyu
# Take batch 1 and batch 2 data as per above example
group_a = [4, 3, 5, 2, 4]
group_b = [3, 2, 4, 3, 3]
  
# perform mann whitney test
stat, p_value = mannwhitneyu(group_a, group_b)
print('Statistics=%.2f, p=%.2f' % (stat, p_value))
# Level of significance
alpha = 0.05
# conclusion
if p_value < alpha:
    print('Reject Null Hypothesis (Significant difference between two samples)')
else:
    print('Do not Reject Null Hypothesis (No significant difference between two samples)')

Statistics=17.00, p=0.38
Do not Reject Null Hypothesis (No significant difference between two samples)


# 16. Scenario: A company wants to analyze the distribution of customer ages. The data collected is as follows:
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
    Calculate the interquartile range (IQR) of the ages.


In [52]:
import numpy as np
  
data = [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
  
# First quartile (Q1)
Q1 = np.median(data[:5])
  
# Third quartile (Q3)
Q3 = np.median(data[5:])
  
# Interquartile range (IQR)
IQR = Q3 - Q1
  
print(IQR)

25.0


# 17. Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.


In [53]:
from scipy import stats
 
# Defining data groups
algo_a = [0.85, 0.80, 0.82, 0.87, 0.83]
algo_b = [0.78, 0.82, 0.84, 0.80, 0.79]
algo_c = [0.90, 0.88, 0.89, 0.86, 0.87]
 
# Conduct the Kruskal-Wallis Test
result = stats.kruskal(algo_a, algo_b, algo_c)
 
# Print the result
print(result)

# In this example, the test statistic comes out to be equal to 9.696 and the corresponding p-value is 0.007. 
# As the p-value is less than 0.05, we can reject the null hypothesis that the median accuracy is not same for all three groups.
# Hence, We  have sufficient proof to claim that the different types of algarithms used statistically significant differences in the accuracy scores.

KruskalResult(statistic=9.696947935368053, pvalue=0.007840333026249539)


# 18. Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:
    Price (in dollars): [10, 15, 12, 8, 14]
    Sales: [100, 80, 90, 110, 95]
    Perform a simple linear regression to predict

 sales based on price.


In [54]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data = pd.DataFrame({'Price':[10, 15, 12, 8, 14],'sales':[100, 80, 90, 110, 95]})
x = data.iloc[: , :-1]
y = data.iloc[: , 1:2]
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=1/3,random_state=0)
regressor = LinearRegression()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test) 
y_pred

array([[ 96.22093023],
       [103.54651163]])

# 19. Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
    Calculate the standard error of the mean satisfaction score.

In [55]:
import math
 
 
 # Function to find sample mean.
def mean(arr, n) :
 
    # loop to calculate
    # sum of array elements.
    sm = 0
    for i in range(0,n) :
        sm = sm + arr[i]
      
    return sm / n
 
 
 # Function to calculate sample
# standard deviation.
def SSD(arr, n) :
    sm = 0
    for i in range(0,n) :
        sm = sm + (arr[i] - mean(arr, n)) * (arr[i] - mean(arr, n))
  
    return (math.sqrt(sm / (n - 1)))
  
  
 # Function to calculate sample error.
def sampleError(arr, n) :
 
    # Formula to find sample error.
    return SSD(arr, n) / (math.sqrt(n))

arr = [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]
n = len(arr)
print(sampleError(arr, n))

0.3055050463303893


# 20. Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]
    Sales (in thousands): [25, 30, 28, 20, 26]
    Perform a multiple regression analysis to predict sales based on advertising expenditure.


In [62]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn import preprocessing


df = pd.DataFrame({'advertising_Expenditure' : [10, 15, 12, 8, 14] , 'Sales' : [25, 30, 28, 20, 26] })

x = df.iloc[: , :-1]
y = df.iloc[: , 1:2]
# creating train and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

# creating a regression model
model = LinearRegression()
  
# fitting the model
model.fit(X_train, y_train)
  
# making predictions
predictions = model.predict(X_test)
  
# model evaluation
print('mean_squared_error : ', mean_squared_error(y_test, predictions))
print('mean_absolute_error : ', mean_absolute_error(y_test, predictions))

mean_squared_error :  8.29772850189292
mean_absolute_error :  2.8720930232558146
